export default [
  {
    rollno:"7376211CS239",
    name: 'Poovarasan S',
    email:"poovarasan.cs21@bitsathy.ac.in",
    credits:"3",
    department:"CSE",
    status: 'success',
    batch:"2025",
    activestatus:"Active",
  },
  {
    rollno:"7376211CS240",
    name: 'John Doe',
    email:"john.doe@example.com",
    credits:"5",
    department:"ECE",
    status: 'success',
    batch:"2025",
    activestatus:"Active",
  },
  {
    rollno:"7376211CS241",
    name: 'Jane Smith',
    email:"jane.smith@example.com",
    credits:"6",
    department:"EEE",
    status: 'success',
    batch:"2027",
    activestatus:"Active",
  },
  {
    rollno:"7376211CS242",
    name: 'Alice Johnson',
    email:"alice.johnson@example.com",
    credits:"8",
    department:"MECH",
    status: 'success',
    batch:"2027",
    activestatus:"Active",
  },
  {
    rollno:"7376211CS243",
    name: 'Bob Brown',
    email:"bob.brown@example.com",
    credits:"4",
    department:"CSE",
    status: 'success',
    batch:"2025",
    activestatus:"Active",
  },
  {
    rollno:"7376211CS244",
    name: 'Emily Davis',
    email:"emily.davis@example.com",
    credits:"2",
    department:"IT",
    status: 'success',
    batch:"2025",
    activestatus:"Active",
  },
  {
    rollno:"7376211CS245",
    name: 'Michael Wilson',
    email:"michael.wilson@example.com",
    credits:"1",
    department:"CSE",
    status: 'success',
    batch:"2026",
    activestatus:"Active",
  },
  {
    rollno:"7376211CS246",
    name: 'Sara Martinez',
    email:"sara.martinez@example.com",
    credits:"5",
    department:"ECE",
    status: 'success',
    batch:"2026",
    activestatus:"Active",
  },
  {
    rollno:"7376211CS247",
    name: 'David Anderson',
    email:"david.anderson@example.com",
    credits:"7",
    department:"EEE",
    status: 'success',
    batch:"2024",
    activestatus:"Active",
  },
  {
    rollno:"7376211CS248",
    name: 'Jessica Thompson',
    email:"jessica.thompson@example.com",
    credits:"8",
    department:"MECH",
    status: 'success',
    batch:"2024",
    activestatus:"Active",
  }
  
];
